# Generated by Django 6.0.3 on 2026-03-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_sqm', models.FloatField(verbose_name='Area (m²)')),
                ('rooms', models.IntegerField(verbose_name='Rooms')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('district', models.CharField(choices=[('Kentron', 'Kentron'), ('Arabkir', 'Arabkir'), ('Davtashen', 'Davtashen'), ('Erebuni', 'Erebuni'), ('Nor Nork', 'Nor Nork')], max_length=50)),
                ('condition', models.CharField(choices=[('Old', 'Old'), ('Normal', 'Normal'), ('New', 'New')], max_length=50)),
                ('predicted_price', models.FloatField(verbose_name='Predicted price (AMD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
