# Generated by Django 6.0.3 on 2026-03-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyevaluation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='propertyevaluation',
            name='area_sqm',
            field=models.FloatField(verbose_name='Մակերեսություն (m²)'),
        ),
        migrations.AlterField(
            model_name='propertyevaluation',
            name='condition',
            field=models.CharField(choices=[('New', 'Նոր վերանորոգված'), ('Normal', 'Լավ վիճակ'), ('Old', 'Վերանորոգման կարիք ունի')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyevaluation',
            name='district',
            field=models.CharField(choices=[('Kentron', 'Կենտրոն'), ('Arabkir', 'Արաբկիր'), ('Avan', 'Ավան'), ('Shengavit', 'Շենգավիտ'), ('Erebuni', 'Էրեբունի')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyevaluation',
            name='floor',
            field=models.IntegerField(verbose_name='Հարկ'),
        ),
        migrations.AlterField(
            model_name='propertyevaluation',
            name='predicted_price',
            field=models.FloatField(verbose_name='Կանխատեսվող Վարձավճար'),
        ),
        migrations.AlterField(
            model_name='propertyevaluation',
            name='rooms',
            field=models.IntegerField(verbose_name='Սենյակների քանակ'),
        ),
    ]
